"""
Data Ingestion Pipeline
========================
Scheduled ETL for Amazon Operations Intelligence Platform.

Runs on Railway as a cron job.
Ingests: settlement reports, orders, returns, inventory, FBA fees, ads.

Usage:
  python -m data.ingestion --store=STORE_02 --mode=settlements
  python -m data.ingestion --store=STORE_02 --mode=all
"""

import argparse
import logging
import os
import sys
from datetime import datetime, timedelta, date
from typing import Optional

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db.connection import get_session, engine
from db.models import (
    FinancialTransaction, CustomerLossEvent,
    Refund, Return,
)
from engines.return_refund_engine import ReturnRefundEngine
from engines.profit_leakage_engine import ProfitLeakageEngine

logger = logging.getLogger("amazon.ingestion")


def run_migrations():
    """Run database migrations (create new tables)."""
    logger.info("Running migrations...")
    with open("db/schema.sql") as f:
        sql = f.read()
    conn = engine.raw_connection()
    try:
        conn.executescript(sql)
        conn.commit()
        logger.info("Migrations complete")
    except Exception as e:
        logger.error(f"Migration error: {e}")
        conn.rollback()
    finally:
        conn.close()


def ingest_settlements(store_id: str):
    """
    Search for and ingest all settlement reports.
    Settlement reports are auto-generated by Amazon — we only SEARCH for them.
    """
    logger.info(f"Ingesting settlements for {store_id}...")

    # Use the Finances API approach (returns data more reliably)
    engine_rr = ReturnRefundEngine(store_id)
    events = engine_rr.fetch_refunds_from_finances(posted_after="2026-01-01T00:00:00Z")
    stored = engine_rr.store_refund_events(events)

    logger.info(f"  Fetched {len(events)} refund events, stored {stored} records")
    return len(events)


def reconcile_losses(store_id: str):
    """Run return/refund reconciliation."""
    logger.info(f"Reconciling losses for {store_id}...")
    engine_rr = ReturnRefundEngine(store_id)
    reconciled = engine_rr.reconcile_loss_events()
    logger.info(f"  Reconciled {reconciled} loss events")
    return reconciled


def scan_profit_leakage(store_id: str):
    """Scan all SKUs for profit leakage."""
    logger.info(f"Scanning profit leakage for {store_id}...")
    engine_pl = ProfitLeakageEngine(store_id)

    # Refresh daily financials for yesterday
    yesterday = date.today() - timedelta(days=1)
    refreshed = engine_pl.refresh_daily_financials(target_date=yesterday)

    # Scan for leakage
    leakage = engine_pl.scan_all_skus(days=30, min_loss=50)

    logger.info(f"  Refreshed {refreshed} daily financials")
    logger.info(f"  Found {len(leakage)} SKUs with leakage")
    return leakage


def full_ingestion(store_id: str):
    """Run all ingestion steps."""
    logger.info(f"=== Full ingestion for {store_id} ===")

    run_migrations()
    n_refunds = ingest_settlements(store_id)
    n_losses = reconcile_losses(store_id)
    leakage = scan_profit_leakage(store_id)

    total_leakage = sum(s.get("leakage", 0) for s in leakage)

    logger.info(f"=== Summary ===")
    logger.info(f"  Refunds ingested:  {n_refunds}")
    logger.info(f"  Loss events:       {n_losses}")
    logger.info(f"  SKUs with leakage: {len(leakage)}")
    logger.info(f"  Total leakage:     ${total_leakage:.2f}")

    return {
        "store_id": store_id,
        "refunds_ingested": n_refunds,
        "losses_reconciled": n_losses,
        "skus_with_leakage": len(leakage),
        "total_leakage": round(total_leakage, 2),
    }


# ─── Store map ───

STORE_MAP = {
    "STORE_01": {"id": "store_01", "name": "Heliumx"},
    "STORE_02": {"id": "store_02", "name": "CUCZZUS"},
    "STORE_03": {"id": "store_03", "name": "BOOLUU"},
    "STORE_04": {"id": "store_04", "name": "Xpike"},
    "STORE_05": {"id": "store_05", "name": "WOC"},
}

MODES = {
    "migrations": run_migrations,
    "settlements": ingest_settlements,
    "reconcile": reconcile_losses,
    "leakage": scan_profit_leakage,
    "all": full_ingestion,
}


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )

    parser = argparse.ArgumentParser(description="Amazon Ops Intel Data Ingestion")
    parser.add_argument("--store", required=True, help="Store env prefix (STORE_01..STORE_05)")
    parser.add_argument("--mode", default="all", choices=list(MODES.keys()), help="Ingestion mode")
    parser.add_argument("--days-back", type=int, default=90, help="Days to look back")

    args = parser.parse_args()

    store = STORE_MAP.get(args.store)
    if not store:
        logger.error(f"Unknown store: {args.store}. Options: {list(STORE_MAP.keys())}")
        sys.exit(1)

    fn = MODES[args.mode]
    if args.mode in ("settlements", "reconcile", "leakage"):
        result = fn(store["id"])
    elif args.mode == "all":
        result = fn(store["id"])
    else:
        result = fn()

    print(f"\n✅ {args.mode.upper()} complete for {store['name']}")
    if isinstance(result, dict):
        for k, v in result.items():
            print(f"   {k}: {v}")
